# Generated by Django 5.1 on 2024-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название стиля')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tattoo',
            options={'verbose_name': 'Татуировка', 'verbose_name_plural': 'Татуировки'},
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='style',
        ),
        migrations.AlterField(
            model_name='tattoo',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
