# Generated by Django 5.1 on 2024-10-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0003_tattoo_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
    ]
