# Generated by Django 5.1 on 2024-10-22 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0005_price_tattoo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Тату мастер')),
            ],
            options={
                'verbose_name': 'Тату мастер',
                'verbose_name_plural': 'Тату мастера',
            },
        ),
        migrations.AddField(
            model_name='tattoo',
            name='tattooArtist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tattoos.tattooartist'),
        ),
    ]
