# Generated by Django 5.1 on 2024-10-22 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0006_tattooartist_tattoo_tattooartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Тату студия')),
            ],
            options={
                'verbose_name': 'Тату студия',
                'verbose_name_plural': 'Тату студии',
            },
        ),
        migrations.AddField(
            model_name='tattooartist',
            name='tattooStudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tattoos.tattoostudio'),
        ),
    ]
