# Generated by Django 5.1 on 2024-11-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0008_tattoo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattooartist',
            name='picture',
            field=models.ImageField(null=True, upload_to='tattooArtists', verbose_name='Изображение'),
        ),
    ]
